# Generated by Django 5.1.5 on 2025-01-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_departments', '0001_initial'),
        ('database_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_organizations.organization'),
        ),
    ]
