# Generated by Django 5.1.5 on 2025-01-28 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Domain have to be 1-63 characters long, contain only alphanumeric characters or hyphens, and must not start or end with a hyphen.', regex='^(?!-)[a-z]{1,63}(?<!-)$')])),
            ],
            options={
                'db_table': 'public"."database_tenants_tenant',
            },
        ),
        migrations.CreateModel(
            name='Tenant2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_tenants.tenant')),
            ],
            options={
                'db_table': 'public"."database_tenants_tenant2user',
            },
        ),
    ]
